DROP TABLE IF EXISTS `LISTING`;
DROP TABLE IF EXISTS `CONTACT`;

CREATE TABLE `LISTING`  (
    `ID`            BIGINT PRIMARY KEY,
    `MAKE`          VARCHAR(100),
    `PRICE`         DOUBLE PRECISION,
    `MILEAGE`       BIGINT,
    `SELLER_TYPE`   VARCHAR(50)
);

CREATE TABLE `CONTACT`
(
    `ID` INTEGER PRIMARY KEY auto_increment,
    `LISTING_ID`    BIGINT NOT NULL,
    `CONTACT_DATE`  BIGINT
);